variables:
  POSTGRES_DB: G4SE
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgres://postgres:postgres@geometalab__g4se-api-db:5432/G4SE
  ELASTIC_SEARCH_URL: http://elasticsearch:9200/
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
#- unit tests
#- integration tests
- integration and unit tests
- build
#- deploy to staging
#-

integration and unit tests:
  stage: integration and unit tests
  image: python:latest
  script:
  - pip install -U pip setuptools
  - pip install -r compass-api/dev-requirements.txt
  - cd compass-api/G4SE/
  - py.test
  services:
  - geometalab/g4se-api-db:latest
  - elasticsearch:1

build docker images:
  image: geometalab/docker-builder
  stage: build
  script:
#  - docker login -u $DOCKERHUB_LOGIN_USERNAME -p $DOCKERHUB_LOGIN_PASSWORD
  - cd compass-frontend
  - npm install
  - rm -rf dist && ng build -prod
  - cd ..
  - docker-compose build
#  - docker-compose push
