version: '2.1'
services:
  frontend:
    image: "geometalab/g4se-frontend:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-frontend/
      dockerfile: Dockerfile
  api:
    image: "geometalab/g4se-api:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api
      dockerfile: Dockerfile
  nginx:
    image: "geometalab/g4se-nginx:${BUILD_VERSION:-latest}"
    build:
      context: ./nginx/
      dockerfile: Dockerfile
  db:
    image: "geometalab/g4se-api-db:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
