version: '2'
services:
  elasticsearch:
    image: elasticsearch:1
    ports:
      - "9200:9200"
  api:
    extends:
      file: common.yml
      service: backend
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=['*']
    links:
      - db:database
      - elasticsearch:elasticsearch
  harvester:
    image: geometalab/g4se-api-harvester
    extends:
      file: common.yml
      service: backend
    command: python3 scheduled_import_geovite.py
    entrypoint: wait_only_docker-entrypoint.sh
    links:
      - db:database
      - elasticsearch:elasticsearch
  db:
    image: geometalab/g4se-api-db
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=G4SE
  frontend:
    image: geometalab/g4se-frontend
    build:
      context: ./compass-frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  nginx:
    image: geometalab/g4se-nginx
    ports:
      - "8080:80"
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
    volumes:
      - api-static:/var/www/g4se-api/static
    environment:
      - VIRTUAL_HOST=localhost,127.0.0.1
volumes:
  api-static: {}
