version: '2.1'
services:
  build-frontend:
    image: node:7.4
    entrypoint: >
      bash -c
      'cd /opt/build/compass-frontend/ &&
      npm install -g angular-cli node-gyp &&
      npm install &&
      rm -rf dist &&
      ng build -prod &&
      chmod -R 0777 dist'
    volumes:
      - ./compass-frontend/:/opt/build/compass-frontend/
  frontend:
    image: "geometalab/g4se-frontend:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-frontend/
      dockerfile: Dockerfile
  api:
    image: "geometalab/g4se-api:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api
      dockerfile: Dockerfile
  nginx:
    image: "geometalab/g4se-nginx:${BUILD_VERSION:-latest}"
    build:
      context: ./nginx/
      dockerfile: Dockerfile
  db:
    image: "geometalab/g4se-api-db:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
