version: '2.1'
services:
  frontend:  # use this in production!
    image: geometalab/g4se-frontend
    ports:
      - "3000:80"
  frontend-development: # do never use this in production!
    image: node:7.4
    ports:
      - "4200:4200"
    command: bash -c 'cd /opt/compass-frontend && npm start'
    volumes:
      - ./compass-frontend:/opt/compass-frontend
    links:
      - "nginx:nginx"
  api:
    image: geometalab/g4se-api
    env_file: .env-api
    entrypoint: /bin/wait_only_docker-entrypoint.sh
    command: uwsgi /uwsgi.ini --processes 2 --threads 1 --py-autoreload=3
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes:
      - api-data:/var/data
      # remove the following line in production!
      - ./compass-api/G4SE:/G4SE
  api-setup:
    image: geometalab/g4se-api
    env_file: .env-api
    command: echo true
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes_from:
      - api
  rq-worker:
    image: geometalab/g4se-api
    env_file: .env-api
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes_from:
      - api
    entrypoint: /bin/wait_only_docker-entrypoint.sh
    command: python3 /G4SE/manage.py rqworker default
  nginx:
    image: geometalab/g4se-nginx
    ports:
      - "8080:80"
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
    volumes:
      - api-data:/var/www/g4se-api
    environment:
      - VIRTUAL_HOST=localhost,127.0.0.1
  db:
    image: geometalab/g4se-api-db
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=G4SE
  elasticsearch:
    image: elasticsearch:1
#    environment:
#      - es.logger.level=TRACE
    ports:
      - "9200:9200"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  api-data: {}
