version: '2'
services:
  frontend:
    image: geometalab/g4se-frontend
    build:
      context: ./compass-frontend/
      dockerfile: Dockerfile
  api:
    image: geometalab/g4se-api
    build:
      context: ./compass-api
      dockerfile: Dockerfile
  nginx:
    image: geometalab/g4se-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
  db:
    image: geometalab/g4se-api-db
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
