version: '2.1'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
  api:
    image: "geometalab/g4se-api:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api/
      dockerfile: Dockerfile
    env_file:
      - .env-api
    entrypoint: /bin/wait_only_docker-entrypoint.sh
    command: uwsgi /uwsgi.ini --processes 2 --threads 1 --py-autoreload=3
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes:
      - api-data:/var/data
      # remove the following lines in production!
      - ./compass-api/G4SE:/G4SE
      - ./expectation_tests:/expectation_tests
  api-setup:
    image: "geometalab/g4se-api:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api/
      dockerfile: Dockerfile
    env_file:
      - .env-api
    command: echo true
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes_from:
      - api
  rq-worker:
    image: "geometalab/g4se-api:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api/
      dockerfile: Dockerfile
    env_file:
      - .env-api
    links:
      - db:database
      - elasticsearch:elasticsearch
      - redis:redis
    volumes_from:
      - api
    entrypoint: /bin/wait_only_docker-entrypoint.sh
    command: python3 /G4SE/manage.py rqworker default
  nginx:
    image: "geometalab/g4se-nginx:${BUILD_VERSION:-latest}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api
    links:
      - api
    volumes:
      - api-data:/var/www/g4se-api
    environment:
      - VIRTUAL_HOST=localhost,127.0.0.1
  nginx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
    volumes:
      - api-data:/var/www/g4se-api
    environment:
      - VIRTUAL_HOST=localhost,127.0.0.1,152.96.214.200
  db:
    image: "geometalab/g4se-api-db:${BUILD_VERSION:-latest}"
    build:
      context: ./compass-api
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=G4SE
  elasticsearch:
    image: elasticsearch:1
#    environment:
#      - es.logger.level=TRACE
  redis:
    image: redis
volumes:
  api-data: {}
