# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('publication_lineage', models.CharField(blank=True, max_length=255, null=True)),
                ('geography', models.CharField(max_length=255)),
                ('extent', models.CharField(max_length=255)),
                ('geodata_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=2083)),
                ('metadata_link', models.CharField(max_length=2083)),
                ('access_link', models.CharField(max_length=2083)),
                ('base_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('arcgis_layer_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('qgis_layer_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('arcgis_symbology_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('qgis_symbology_link', models.CharField(blank=True, max_length=2083, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('crs', models.CharField(max_length=20)),
                ('term_link', models.CharField(max_length=2083)),
                ('proved', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(max_length=255)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('login_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
    ]
