# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:46
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedRecord',
            fields=[
                ('api_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_year', models.CharField(max_length=20)),
                ('publication_lineage', models.CharField(blank=True, max_length=255, null=True)),
                ('geography', models.CharField(max_length=255)),
                ('extent', models.CharField(max_length=255, null=True)),
                ('geodata_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=2083)),
                ('metadata_link', models.URLField(max_length=2083)),
                ('access_link', models.URLField(max_length=2083)),
                ('base_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('arcgis_layer_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('qgis_layer_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('arcgis_symbology_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('qgis_symbology_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('crs', models.CharField(max_length=20)),
                ('term_link', models.URLField(max_length=2083)),
                ('proved', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('test', 'test'), ('hsr-internal', 'hsr-internal')], default='public', max_length=255)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('login_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector_de', django.contrib.postgres.search.SearchVectorField()),
                ('search_vector_en', django.contrib.postgres.search.SearchVectorField()),
                ('search_vector_fr', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'db_table': 'all_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestedRecord',
            fields=[
                ('api_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_year', models.CharField(max_length=20)),
                ('publication_lineage', models.CharField(blank=True, max_length=255, null=True)),
                ('geography', models.CharField(max_length=255)),
                ('extent', models.CharField(max_length=255, null=True)),
                ('geodata_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=2083)),
                ('metadata_link', models.URLField(max_length=2083)),
                ('access_link', models.URLField(max_length=2083)),
                ('base_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('arcgis_layer_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('qgis_layer_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('arcgis_symbology_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('qgis_symbology_link', models.URLField(blank=True, max_length=2083, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('crs', models.CharField(max_length=20)),
                ('term_link', models.URLField(max_length=2083)),
                ('proved', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('test', 'test'), ('hsr-internal', 'hsr-internal')], default='public', max_length=255)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('login_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector_de', django.contrib.postgres.search.SearchVectorField()),
                ('search_vector_en', django.contrib.postgres.search.SearchVectorField()),
                ('search_vector_fr', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'db_table': 'harvested_records',
                'managed': False,
            },
        ),
    ]
