# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recordtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtag',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
    ]
