# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161010_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServiceMetadataTagItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_service_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GeoServiceMetadata')),
            ],
        ),
        migrations.RemoveField(
            model_name='recordtag',
            name='tag_de_search_vector',
        ),
        migrations.RemoveField(
            model_name='recordtag',
            name='tag_en_search_vector',
        ),
        migrations.RemoveField(
            model_name='recordtag',
            name='tag_fr_search_vector',
        ),
        migrations.AddField(
            model_name='geoservicemetadatatagitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RecordTag'),
        ),
    ]
