# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161011_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordTag',
            new_name='TranslationTag',
        ),
    ]
