# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 17:10
from __future__ import unicode_literals

from django.db import migrations



create_update_tsv_function = """
CREATE OR REPLACE FUNCTION {function_name}()
RETURNS TRIGGER AS $$
BEGIN
    NEW.tag_{lang}_search_vector := to_tsvector('pg_catalog.{pg_lang}', array_to_string(NEW.tag_alternatives_{lang}, ' ')) ||
    to_tsvector('pg_catalog.{pg_lang}', NEW.tag_{lang});
    RETURN NEW;
END;
$$ language 'plpgsql';
"""

add_trigger = """
CREATE TRIGGER {trigger_name} BEFORE INSERT OR UPDATE
    ON {table} FOR EACH ROW EXECUTE PROCEDURE {function_name}();
"""


remove_trigger = """
DROP TRIGGER IF EXISTS {trigger_name} ON {table};
"""

remove_function = """
DROP FUNCTION IF EXISTS {function_name}();
"""

FUNCTION_BASE_NAME = 'tsvector_update_'
TRIGGER_BASE_NAME = 'tsvector_trigger_'


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161011_1506'),
    ]

    operations = [
        migrations.RunSQL(
            [
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_de', table='record_tag')),
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_en', table='record_tag')),
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_fr', table='record_tag')),
                (remove_function.format(function_name=FUNCTION_BASE_NAME + 'tag_de')),
                (remove_function.format(function_name=FUNCTION_BASE_NAME + 'tag_en')),
                (remove_function.format(function_name=FUNCTION_BASE_NAME + 'tag_fr')),
            ],
            [
                (create_update_tsv_function.format(trigger_name=TRIGGER_BASE_NAME + 'tag_de', table='record_tag',
                                                   function_name=FUNCTION_BASE_NAME + 'tag_de', pg_lang='german',
                                                   lang='de')),
                (create_update_tsv_function.format(trigger_name=TRIGGER_BASE_NAME + 'tag_en', table='record_tag',
                                                   function_name=FUNCTION_BASE_NAME + 'tag_en', pg_lang='english',
                                                   lang='en')),
                (create_update_tsv_function.format(trigger_name=TRIGGER_BASE_NAME + 'tag_fr', table='record_tag',
                                                   function_name=FUNCTION_BASE_NAME + 'tag_fr', pg_lang='french',
                                                   lang='fr')),
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_de', table='record_tag')),
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_en', table='record_tag')),
                (remove_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_fr', table='record_tag')),
                (add_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_de', table='record_tag',
                                    function_name=FUNCTION_BASE_NAME + 'tag_de')),
                (add_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_en', table='record_tag',
                                    function_name=FUNCTION_BASE_NAME + 'tag_en')),
                (add_trigger.format(trigger_name=TRIGGER_BASE_NAME + 'tag_fr', table='record_tag',
                                    function_name=FUNCTION_BASE_NAME + 'tag_fr')),
            ]

        )
    ]
