# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 07:47
from __future__ import unicode_literals

from django.db import migrations

drop_harvested_records = [
    "DROP TRIGGER harvested_tsvectorupdate_de ON harvested_records;",
    "DROP TRIGGER harvested_tsvectorupdate_en ON harvested_records;",
    "DROP TRIGGER harvested_tsvectorupdate_fr ON harvested_records",
    "DROP TABLE harvested_records;",

]

drop_records = [
    "DROP TRIGGER tsvectorupdate_en ON records;",
    "DROP TRIGGER tsvectorupdate_de ON records;",
    "DROP TRIGGER tsvectorupdate_fr ON records;",
    "DROP TABLE records;",
]

drop_trigger_functions = [
    "DROP FUNCTION records_trigger_de();",
    "DROP FUNCTION records_trigger_en();",
    "DROP FUNCTION records_trigger_fr();",

    "DROP FUNCTION harvested_records_trigger_de();",
    "DROP FUNCTION harvested_records_trigger_en();",
    "DROP FUNCTION harvested_records_trigger_fr();",
]


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_drop_obsolete_view_20161012_0726'),
    ]

    operations = [
        migrations.RunSQL(drop_harvested_records),
        migrations.RunSQL(drop_records),
        migrations.RunSQL(drop_trigger_functions),
        migrations.DeleteModel(name='RecordTaggedItem'),
        migrations.DeleteModel(name='CombinedRecord'),
        migrations.DeleteModel(name='Record'),
        migrations.DeleteModel(name='RecordTag'),
        migrations.DeleteModel(name='HarvestedRecord'),
    ]
