# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161012_0905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='translationtag',
            table=None,
        ),
    ]
