# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161012_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoservicemetadata',
            name='publication_lineage',
            field=models.TextField(blank=True, null=True, verbose_name='history'),
        ),
    ]
