# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_switch_to_null_boolean_field_20161110_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoVITeImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_zip', models.FileField(help_text='not existing files will be deleted', upload_to='', verbose_name='zipped GeoVite XML files')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modification')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('in_use', models.BooleanField(help_text='is this data in use currently, there can only be one at a time', verbose_name='in use')),
            ],
        ),
    ]
