FROM postgres:9.5
MAINTAINER Geometalab <geometalab@hsr.ch>

RUN apt-get update && apt-get install -y \
    postgis \
    && rm -rf /var/lib/apt/lists/*

ADD setup_database.sql /docker-entrypoint-initdb.d/000_setup_database.sql

