data = {
    "identifier": "1234567",
    "language": "de",
    "content": "Topologisches Landschaftsmodell TLM, Fliessgewässer",
    "abstract": "swissTLM3D ist das grossmassstäbliche Topografische Landschaftsmodell der Schweiz. Es umfasst die natürlichen und künstlichen Objekte wie auch die Namendaten in vektorieller Form. Mit einer hohen Genauigkeit und dem Einbezug der dritten Dimension ist swissTLM3D der genaueste und umfassendste 3D-Vektordatensatz der Schweiz. In dieser Feature Class werden die Fliessgewässer in linearer Form geführt. Die Linien sind in Richtung des Gewässerflusses gerichtet.",
    "publication_year": 2012,
    "publication_lineage": "2015, 2014, 2012",
    "geography": "Schweiz",
    "extent": "BOX(5.9335 45.7785,10.6891 47.839)",
    "geodata_type": "vector",
    "source": "Swisstopo",
    "metadata_link": "http://www.swisstopo.admin.ch/internet/swisstopo/de/home/products/landscape/swissTLM3D.parsysrelated1.47641.downloadList.97108.DownloadFile.tmp/201603swisstlm3d14okd.pdf",
    "access_link": "https://geodata4edu.hsr.ch/geodata/rest/services/swissTLM3D/TLM_FLIESSGEWAESSER/FeatureServer",
    "base_link": "https://geodata4edu.hsr.ch/geodata/rest/services/swissTLM3D/TLM_FLIESSGEWAESSER/FeatureServer",
    "collection": "/swissTLM3D/",
    "dataset": "TLM_FLIESSGEWAESSER",
    "arcgis_layer_link": "https://geodata4edu.hsr.ch/share/TLM_FLIESSGEWAESSER.pitem",
    "qgis_layer_link": "",
    "arcgis_symbology_link": "https://geodata4edu.hsr.ch/share/TLM_FLIESSGEWAESSER.lyr",
    "qgis_symbology_link": "https://geodata4edu.hsr.ch/share/TLM_FLIESSGEWAESSER_QGIS.zip",
    "service_type": "FeatureService",
    "crs": "EPSG:21781",
    "term_link": "http://www.swisstopo.admin.ch/internet/swisstopo/de/home/swisstopo/legal_bases/copyright.html",
    "proved": "2015-03-04",
    "visibility": "public",
    "login_name": ""
}